### ISSUE TITLE
Handle nil/empty values from store during comparisons

### ISSUE THREAD

**Issue by jheth** [rubysolo/dentaku#16]
I just came across your project today and am really excited. It's just the project I was looking for.  I'm running into an error when a value is nil or does not exist.

The Hash that I'm using for the calculator.store will sometimes have nil or non-existent values that the expression relies on.  This causes "price > 15000" to error if 'price' does not exist or is nil.    Error:  undefined method `>' for nil:NilClass  (this would be the same error for any operator that doesn't support nil)

How would you suggest handling this situation?

**Comment by systemed** [comment]
The fix in https://github.com/rubysolo/dentaku/commit/ccb0c5a8c163c32e032b108fb6ab917c9ef9dd89 resolves the entire expression as :foo.

This is a bit helpful, but it would be better, I think, to resolve individual unbound variables. So to take the example above, `calculator.evaluate('a+1') { 0 }` would return 1, rather than 0 as at present.

In particular, this would help with IF clauses and similar: `IF(1==1,a,b)` currently falls back to the default value if `b` is undefined, even though the condition is always `true`.

I've fixed it for my use-case by monkeypatching but thought I'd offer the suggestion.

(Apologies for necroposting!)

**Comment by rubysolo** [comment]
Hmm, I need to think a bit more about this.  The original idea for the block was so that the end-user could do custom error handling for unbound variables and then return some final result.  How would it look if there were multiple unbound variables?

I agree that `IF` statements should ignore unbound variables in the unused branch if the predicate value is resolvable, though -- I'll make that change when I can.

**Comment by eddymund** [comment]
I have the use case where I want to resolve individual unbound variables in order to make expressions like `A + B` resolve to 0 even if A and B were unbound. 

Maybe consider passing in default values when calling the function, e.g. `evaluate(expression, data, defaults)` to allow the user to pass in defaults like `evaluate("A + B", {}, { A: 0, B: 0 })`.

Another use case that I have is that for blank variable arguments in functions, I do not want to use default values while still not wanting to raise an unbound error. For example, if I have call `evaluate("AVG(A, B, C)", { A: 1, B: 2 })`, I want it to evaluate to 0.75 based on the non-blank values.

Sorry for piggybacking onto a closed issue but I saw that there was some discussion about resolving individual unbound variables and I thought I would throw in my two cents.

**Comment by rubysolo** [comment]
Hi @eddymund --

Could you handle the first use case by merging your actual values over your defaults?

```ruby
defaults = { A: 0, B: 0 }
actuals = { A: 1 }
evaluate("A + B", defaults.merge(actuals))
```

For the second use case, can you explain a little more about how it would get to the 0.75 value?

**Comment by eddymund** [comment]
It's true that merging the actual values over my defaults would work for my first use case, but it doesn't quite work for my second use case, in which I need to know if the real value was blank or not.

In my second use case, `evaluate("AVG(A, B, C)", { A: 1, B: 2 })` would evaluate to 0.75 because even though there are three variables, only two are non-blank, so I would want my function to return `(1+2)/2` instead of `(1+2+0)/3`, which is why I want to avoid using default values blindly. 

For my second use case, I managed to get by through explicitly passing `nil` as the value to blank variables and redefining some of the functions to ignore `nil` values (e.g. `args.flatten.compact`). However, with default values, it becomes more complicated because there are cases when I want to use default values and when I don't.
