### ISSUE TITLE
Random "no value provided for variables" even if value was provided

### ISSUE THREAD

**Issue by thorstenspringhart** [rubysolo/dentaku#216]
Hi,
Using version 3.3.4

In my rails app i have different formulas to convert some units with the following method:

```
  def self.convert(formula, value)
    Dentaku.enable_ast_cache!
    Dentaku!(formula, value: value)
  rescue StandardError => e
    puts "Error while converting unit: formula '#{formula}', value '#{value}': #{e.message}"
  end
```

Sometimes (I was not able to reproduce, but it happens from time to time), i got errors with really simple formulas, like:

 _Error while converting unit:  formula 'value - 273.15', value '298.365088': no value provided for variables: value_

As mentioned, if to this manually in the console e.g, it works fine and looking at the log, i a pretty sure there was a value provided.

Any idea what could cause this failure?

**Comment by rubysolo** [comment]
No, this seems very strange.  Can you give me more context?  Does it only happen in the production environment?  If so, how is that environment configured?

**Comment by marcoroth** [comment]
Hey @rubysolo

I work with Throsten and investigated a little bit where the issue is coming from. I was able to reproduce the behavior on current `master` (d77dd3bc68e68f10d6275aa1889e0379825890f3).

We are running our app on Heroku with multiple dynos. 

It seems that there is a part in Dentaku which is not "thread safe" per default. Changing it from `Dentaku!(formula, value: value)` to `Dentaku.evaluate!(formula, value: value)` seems to reduce the likelyness for it to occur. 

I tested a lot of stuff to fix the issue directly in the library. My research showed, that the line `unbound = node.dependencies - memory.keys` seems to cause the issue in `lib/dentaku/calculator.rb:62`. 

https://github.com/rubysolo/dentaku/blob/d77dd3bc68e68f10d6275aa1889e0379825890f3/lib/dentaku/calculator.rb#L60-L65

In our exception case `node.dependencies` is an array (`['value']`) and `memory.keys` is also an array (`['value']`). So the result in `unbound` should be `[]`. However the result in `unbound` still remains `['value']` which leads to our error `Dentaku::UnboundVariableError: no value provided for variables: value`.

When the error pops up we can safley rerun the operation in the rescue block and it works as it should. I tested that a few times. Running the excact operation in the rescue block seemed to have worked every time. I conclude that it has to do with the execution and not the formula or value itself.

Along the way I also came across these errors: `Dentaku::AST::Division has too many operands`, `Dentaku::AST::Multiplication has too many operands` and `too many opening parentheses` which seem to be interchangeable.

It doesn't seem to have an impact which formula or value you use, but the following factors seem to influence to result in one way or another:

* Complexity of the formula 
* wheter you use a BigDecimal values or not
* The amount of threads/current executions
* The amount of calculations

I can reliably provoke the error with the following script on Ruby 2.7.2:

```ruby
require "dentaku"

formula = '(value * 1233.48179999732) + 0.0'
value = BigDecimal('0.197843993573542e20')

threads = []

Dentaku.enable_ast_cache!

8.times do
  threads << Thread.new do
    1_000_000.times do
      Dentaku!(formula, value: value)
    end
  end
end

threads.each(&:join)
```

(I know the numbers are a little bit high, but for provoking the error in development it works more reliably)

I hope this helps narrowing down the issue. 

Thanks a lot!

**Comment by rubysolo** [comment]
Thanks for digging into this!  I can't reproduce it locally on `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]`, but I pushed up a [threadsafe](https://github.com/rubysolo/dentaku/tree/threadsafe) branch that should coordinate access to the calculator instance.  Can you give that a try with your reproduction script and see if it fixes things?

**Comment by marcoroth** [comment]
Thank you for the fast investigation! Interesting - I'm on `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin18]`.

The `threadsafe` branch looks good. I can at least verify that this actually solves the issues I was seeing in my local reproduction script.
