### ISSUE TITLE
Improve performance of "if" function?

### ISSUE THREAD

**Issue by mockaroo** [rubysolo/dentaku#44]
I noticed that the "if" function is quite a bit slower than some others such as arithmetic operations.  I was wondering if the author sees any obvious performance bottlenecks in the implementation of that function that might be improved.  I'm using the code below as a simple benchmark and noticing it take quite a bit longer than the equivalent ruby code.

```ruby
10000.times { calc.evaluate('if (a > b and a > c, a, c)', a:1, b:2, c:3) }
```

I dug into the source a bit myself but didn't see anything obvious.  Thanks in advance and thank you for this amazing library!

**Comment by rubysolo** [comment]
The only thing that comes to mind is that since the current algorithm is replacement-based, both branches of the IF statement have to be evaluated regardless of the conditional.  It would be good to switch to a tree-based representation and then only evaluate one branch or the other, but that's a large change.

**Comment by rubysolo** [comment]
v2.0 implements AST caching and short-circuit evaluation for `if`.  Please try again with `Dentaku.enable_ast_cache!` before your benchmark code is evaluated.  I'm going to close this for now -- if it's still an issue, feel free to re-open with your findings.

**Comment by mensfeld** [comment]
@rubysolo  is the short circuit available for `AND` operations as well?
