### ISSUE TITLE
Different behavior with unbound variables between evaluate and solve!

### ISSUE THREAD

**Issue by glanotte** [rubysolo/dentaku#47]
When you execute, with `x` unbound

```
calculator.evaluate("x+1")
#=> nil
calculator.solve!(y: "x+1")
#> {"x" => 1}
```

I was curious if this was desired behavior? Personally, I would prefer the `nil` option but I wanted to see what you all thought. The `!` would tend to indicate an error, but I was hoping to avoid those (see my other ticket https://github.com/rubysolo/dentaku/issues/46).

Again, I am happy to submit a PR but wanted to run it through you all. Thanks for the gem, saved me a ton of time :)

Thanks! Geoff

**Comment by rubysolo** [comment]
Yikes, this is clearly **wrong**.  In an ideal world, I think `solve` should return the values that it can and then either `nil` or some error value for the others.  Something like:

```ruby
calculator.solve(y: "x+1")
#=> {y: nil}
calculator.solve(y: "x+1", z: "5+3")
#=> {y: nil, z: 8}
```
(or alternatively something like `Dentaku::UnboundVariableError` instead of the nils)

Then `solve!` could just raise the error and fail fast.

What do you think?

**Comment by glanotte** [comment]
I like differentiating between `solve` and `solve!` where `solve!` raises an error and `solve` returns `nil` which would follow the behavior of `evaluate` and `evaluate!`.
